mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'polls/',include('poll.urls')),
]

mysite/poll/urls.py
from django.conf.urls import url
from . import views

app_name = 'poll'
urlpatterns = [
    url(r'^$',views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$' , views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$' , views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$' , views.vote, name='vote'),
    

    

    ]

mysite/poll/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date =  models.DateTimeField()

    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/poll/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from poll.models import Question, Choice
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic


# Create your views here.

class IndexView(generic.ListView):
    template_name = 'poll/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

'''
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    return render(request,'poll/index.html',{'latest_question_list':latest_question_list})
    #With render we do not need loader to get the template.
    #And we do not need HttpResponse to load the page.


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('poll\index.html')
    context = {'latest_question_list':latest_question_list}
    return HttpResponse(template.render(context, request))
    #With render we do not need loader to get the template.
    #And we do not need HttpResponse to load the page.
'''
'''
def results(request, question_id):
    response = "You're looking at the results of question {}."
    return HttpResponse(response.format(question_id))
'''
class DetailView(generic.DetailView):
    model = Question
    template_name = 'poll/detail.html'

'''
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'poll/detail.html', {'question':question})


def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    
    return render(request, 'poll/detail.html',{'question':question})
'''

'''def vote(request, question_id):
    return HttpResponse("You're voting on question {}".format(question_id))'''

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'poll/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('poll:results', args=(question.id,)))
'''
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'poll/results.html', {'question': question})
'''
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'poll/results.html'

mysite/poll/templates/poll/detail.html
        <a href="{%url 'poll:index' %}"> <h1>{{ question.question_text }}</h1> </a>
        {% if error_message %}<p>{{ error_message }}</p>{% endif %}
        
        <form action="{% url 'poll:vote' question.id %}" method="POST">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
        {% endfor %}
        <input type="submit" value="Vote" />
        </form>
  

mysite/poll/templates/poll/index.html
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'poll/poll.css' %}">
        <title>Polls</title>
    </head>
    <body>
        <h1>Index of Polls</h1>
        {% if latest_question_list %}
            <ul>
            {% for question in latest_question_list %}
                <li><a href="{%url 'poll:detail' question.id%}">{{ question.question_text }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
</html>

mysite/poll/templates/poll/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'poll:detail' question.id %}">Vote again?</a>